### ISSUE TITLE
Ease of assembly for diy

### ISSUE THREAD

**Issue by Giorgio-BE** [hanshuebner/AppleII-VGA#1]
Hi,

I was thinking about making the PCB a 2-layer layout when I noticed your work.  I'm only a starter so I'm very happy somebody with more experience was already on it.  There are 1 difference between what you are doing and what I had in mind so I wonder if you might consider changing your design:
in my humble opinion diy people often don't have experience (or the necessary tools to deal) with SMD components and are already very happy if they can correctly mount THT components.  At the other side I appreciate projects which stay as close as possible to components which were available when the Apple II was produced.  So another reason to for example user THT capacitors and resistors and ICs.  
Any change going that way and for example use 74LS245 as in the original design made by Mark Aikens?

greetz

**Comment by hanshuebner** [comment]
Hi @Giorgio-BE,

thank you for your feedback.  I personally don't like using THT components anymore - I was scared of using them for 30 years but after I have switched, I'm not looking back.  Redesigning the board for THT parts would not be too difficult, but I'm not motivated to do that myself.

The 74LCX16245 that is used in my design is a effectively two 5V tolerant 74LVC245 in one package.  In a THT version, you would probably want to go with 74LVC245 in the DIP package.  They're relatively cheap and easy to find.

Thank you for your feedback!
Hans

**Comment by hanshuebner** [comment]
@mamejay The PCB's arrived this week, but I'm traveling.  I'll be able to build one next week and will report how that goes.

**Comment by Verault** [comment]
Cant wait and fingers crossed!

**Comment by hanshuebner** [comment]
PCBs have arrived and I'm in the testing process.

**Comment by mamejay** [comment]
So how is it looking or are you just soldering them together at this stage?  Will be placing a PCB order in a week or 2 for a few things and want to add a batch of these to the order.

**Comment by hanshuebner** [comment]
I have VGA output but the bus snooping does not work yet.  I'll try to find out what's wrong in the next couple of days.

**Comment by hanshuebner** [comment]
My PCBs work!  I had to reset the Apple once to make the Pico pick up the signal, but everything worked fine from that point on.  No patches required.  I have only tried VGA so far.
