### ISSUE TITLE
CP/M version

### ISSUE THREAD

**Issue by rallepalaveev** [hanshuebner/AppleII-VGA#11]
May I kindly ask if there is any particular CP/M version which should be used with the Z80 firmware?

**Comment by hanshuebner** [comment]
I don't know whether there is a particular version of CP/M that needs to be used with the Z80 firmware.  I must admit that I've not tried it myself - Did you check out the parent repository for information?  What did you try and how did it now work?

**Comment by hanshuebner** [comment]
The VGA adapter does not need the PAL to work.  I don't have experience with PAL programming myself, so I don't know whether and how a 22V10 will work as a replacement.  I'd try to measure, but do ask upstream for what CP/M is supposed to work with the Z80 code.

**Comment by rallepalaveev** [comment]
Yes, thanks, I know for VGA no PAL i needed, but with PAL, the VGA should still work. And it does. I just want to get the Z80 functionality up and running, and as I have no experience with CPM, I just want to see if anyone has got it working. Thanks!
