### ISSUE TITLE
Need help with Z80 firmware

### ISSUE THREAD

**Issue by rallepalaveev** [hanshuebner/AppleII-VGA#12]
Hi, I have built the card with VGA functionality with the PLD and it works well. However, when I flash the Z80 firmware, CPM cannot boot as it says it can't find a Z80 card. Is there anything special way to activate the Z80 firmware?

The PLD I use is ATF22V10, below are 2 of my codes whic work with VGA. I tried a variety of tweaks, but to no avail.

PIN [1..11]     = [A0..10];
PIN 13          = IOSEL;
PIN 14          = DEVSEL;
PIN 15          = SEL;
PIN 16          = RESET;
PIN 17          = IOSTR;
PIN [18..21]    = [BSEL3..0];
PIN 22          = EXTENABLE;
PIN 23          = EXTDISABLE;
EXTDISABLE = !(EXTENABLE # !IOSEL);
EXTENABLE = !(EXTDISABLE # !RESET # (!IOSTR & [A10..0]:'b'11111111111 & [BSEL3..0]:'b'101X) # [BSEL3..0]:'b'0111);
SEL = DEVSEL & IOSEL & (!EXTENABLE # IOSTR);

-----------------------

PIN [1..11]     = [A0..10];
PIN 13          = IOSEL;
PIN 14          = DEVSEL;
PIN 15          = SEL;
PIN 16          = RESET;
PIN 17          = IOSTR;
PIN [18..21]    = [BSEL3..0];
PIN 22          = EXTENABLE;
EXTENABLE       = (EXTENABLE & RESET & !(!IOSTR & [A10..0]:'b'11111111111 & [BSEL3..0]:'b'101X) & ![BSEL3..0]:'b'0111) # !IOSEL;
SEL = DEVSEL & IOSEL & (!EXTENABLE # IOSTR);

Thank you.

**Comment by hanshuebner** [comment]
What Z80 firmware did you flash?

**Comment by rallepalaveev** [comment]
I used the modular firmware v2-analog-lc-4ns-z80.uf2 of the latest release.

**Comment by rallepalaveev** [comment]
Maybe I am not flashing it correctly? For VGA I do the pre-loader first and then immediately the VGA firmware. I tried the same for the Z80, also tried the original nuke.uf2 from RPI and then the FW, but nothing seems to be helping.

**Comment by rallepalaveev** [comment]
I read some posts in forum.classic-computing.de, looks like I need the release of 19-Jan-2023, I wonder where this can be found?
