### ISSUE TITLE
Wrong footprint for TSSOP-48 buffers

### ISSUE THREAD

**Issue by hanshuebner** [hanshuebner/AppleII-VGA#2]
Too wide, barely works.

**Comment by mamejay** [comment]
Oh no!!  So are the chips too big or the footprint too wide?  Can you at least get the buffers soldered on for testing?

**Comment by hanshuebner** [comment]
> Oh no!! So are the chips too big or the footprint too wide? Can you at least get the buffers soldered on for testing?

The footprint is too wide, but it still works.  I'm just opening issues to remind me what to fix when I make another revision.

**Comment by Verault** [comment]
When will you release a new set of gerbers with the correct footprint for the IC's now that the preliminary tests work?

**Comment by hanshuebner** [comment]
> When will you release a new set of gerbers with the correct footprint for the IC's now that the preliminary tests work?

I cannot make any promises, it will probably take me another 2-3 weeks.  For hand-soldering, the current layout is good enough.  It requires precision when placing the two TSSOP48 ICs as the overlap between the legs and the pads is only about 1mm on each side.

I have heard it before and now I'll know better next time:  All footprints in KiCAD need to be checked before used, as some of them are just off.  The DB15HD footprint is another example, but I've fixed that on this layout already.

**Comment by Verault** [comment]
I do intend to hand solder, but I am in no rush and can continue to wait for the updated gerbers. I appreciate you doing these prelimininary test builds just for this purpose.

**Comment by mamejay** [comment]
Hello again. I see you closed the initial issue stating that the boards actually work.  So if I modify that footprint and bring the footprint 1mm closer together they should be ok?

**Comment by hanshuebner** [comment]
> if I modify that footprint and bring the footprint 1mm closer together they should be ok?

Yes.  Things look good except for the footprint.

**Comment by mamejay** [comment]
OK.  I am terrible with Kicad so will just  wait for you to sort this out.
I want to use the follow.
https://www.lcsc.com/product-detail/Buffer-Driver-Transceiver_onsemi-74LCX16245MTD_C894789.html
Going by the data sheet and checking the footprint editor the one you selected should be spot on.
Bit confused

**Comment by hanshuebner** [comment]
I've just taken care of it and will upload a new rev in a couple minutes.  I've taken care to get it right, but I have not tested it myself, obviously.
