### ISSUE TITLE
Need some assistance finding the correct bat54

### ISSUE THREAD

**Issue by Verault** [hanshuebner/AppleII-VGA#7]
I have already purchased two types of bat54 which are wrong. Could you please recommend the proper part for this build? Also I am looking at the pcb and I am not seeing anything designating which way to place the bat54. I assume it could only be placed one way properly.

**Comment by hanshuebner** [comment]
The BAT54 is non-critical, any low-drop diode can be used, and you could even get away with a 1N4148.  The cathode is indicated by stripes on the plastic case or by a black ring with a glass diode, and it needs to be on the left, where the silkscreen marking has a vertical line.
